(function(){
var inviteState={pendingInvite:null};
function safeHtml(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}
function cutePhrase(){var list=["My forever","Love awaits","Us always","Only us","Sweet destiny","Pure forever"];return list[Math.floor(Math.random()*list.length)]}
function ensureFlowCards(){var card=document.querySelector(".auth-card");if(!card)return;if(!document.getElementById("invite-wait-step")){var w=document.createElement("div");w.id="invite-wait-step";w.className="hidden";card.appendChild(w)}if(!document.getElementById("invite-response-step")){var r=document.createElement("div");r.id="invite-response-step";r.className="hidden";card.appendChild(r)}}
function hideAuthSteps(){["phone-step","otp-step","setup-step","invite-wait-step","invite-response-step"].forEach(function(id){var el=document.getElementById(id);if(el)el.classList.add("hidden")})}
function showAuthSection(id){document.getElementById("auth").classList.remove("hidden");document.getElementById("app").classList.add("hidden");hideAuthSteps();var el=document.getElementById(id);if(el)el.classList.remove("hidden")}
function inviteLink(id){return window.location.origin+window.location.pathname+"?invite="+encodeURIComponent(id)}
function queryInviteId(){return new URLSearchParams(window.location.search).get("invite")}
function clearInviteQuery(){var u=new URL(window.location.href);u.searchParams.delete("invite");window.history.replaceState({}, "", u.toString())}
function ensureItemId(item,prefix){if(item&&!item.id)item.id=(prefix||"item")+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,8);return item}
function normalizeAppData(data){var next={calendarEvents:[],bucketList:[],travelList:[],babyNames:[],loveNotes:[],memories:[],customDateIdeas:[],favorites:{},intimateEntries:[],intimateWishlist:[]};Object.keys(next).forEach(function(k){if(data&&data[k]!=null)next[k]=data[k]});["calendarEvents","bucketList","travelList","babyNames","loveNotes","memories","customDateIdeas","intimateEntries","intimateWishlist"].forEach(function(k){next[k]=(next[k]||[]).map(function(item){return ensureItemId(item,k.slice(0,-1))})});return next}
function setMessage(type,msg){var c=document.getElementById("message-container"),box=document.createElement("div");if(!c)return;c.innerHTML="";box.className=type==="error"?"error-message":"success-message";box.textContent=msg;c.appendChild(box);setTimeout(function(){if(c.contains(box))c.removeChild(box)},5000)}
showError=function(msg){setMessage("error",msg)};
showSuccess=function(msg){setMessage("success",msg)};
function relId(a,b){return[a,b].sort().join("__").replace(/[^\w]/g,"_")}
function openRelationshipFor(phone,currentId){return db.collection("relationships").where("members","array-contains",phone).get().then(function(snap){var found=null;snap.forEach(function(doc){var d=doc.data()||{},status=d.status||"active";if(!found&&status!=="rejected"&&status!=="cancelled"&&status!=="declined"&&(!currentId||doc.id!==currentId))found={id:doc.id,data:d}});return found})}
function pendingInviteFor(phone){return db.collection("invites").where("partnerPhone","==",phone).get().then(function(snap){var found=null;snap.forEach(function(doc){var d=doc.data()||{};if(!found&&d.status==="pending")found={id:doc.id,data:d}});return found})}
function inviteById(id){return db.collection("invites").doc(id).get().then(function(doc){if(!doc.exists)return null;return{id:doc.id,data:doc.data()||{}}})}
function resetSetupButton(){var btn=document.getElementById("setup-btn-text");if(btn)btn.textContent="Start Our Forever Journey"}
function waitingUi(invite){ensureFlowCards();var step=document.getElementById("invite-wait-step"),phrase=invite.data.cuteMessage||cutePhrase(),link=invite.data.link||inviteLink(invite.id);step.innerHTML='<div class="info-box"><div class="info-title">Invite Created</div><div class="info-text">A pending loyalty invite is ready for <strong>'+safeHtml(invite.data.partnerPhone)+'</strong>. Ask your partner to sign in with Firebase OTP on this app. When they open the invite link and verify their number, they can accept it.</div></div><div class="input-group"><label class="input-label">Cute Message</label><input type="text" value="'+safeHtml(phrase)+'" readonly></div><button class="btn btn-outline" onclick="window.__inviteActions.copyLink()">Copy Invite Link</button><div class="info-box" style="margin-top:18px;"><div class="info-title">OTP Only</div><div class="info-text">This version uses Firebase OTP only. Invite delivery is manual: share the link yourself, then your partner verifies their phone and accepts.</div></div>';window.__inviteActions={copyLink:function(){navigator.clipboard.writeText(link).then(function(){showSuccess("Invite link copied!")})}};inviteState.pendingInvite=invite;showAuthSection("invite-wait-step")}
function incomingUi(invite){ensureFlowCards();var step=document.getElementById("invite-response-step");step.innerHTML='<div class="info-box"><div class="info-title">Love Invite</div><div class="info-text"><strong>'+safeHtml(invite.data.inviterName||"Someone")+'</strong> invited you to join their loyalty space.<br><br><em>'+safeHtml(invite.data.cuteMessage||cutePhrase())+'</em></div></div><button class="btn" onclick="acceptInviteFlow()">Accept Invite</button><button class="btn btn-outline" onclick="declineInviteFlow()">Decline</button>';inviteState.pendingInvite=invite;showAuthSection("invite-response-step")}
function loadRelationshipByIdPatched(id){currentRelationshipId=id;return db.collection("relationships").doc(id).get().then(function(relDoc){if(!relDoc.exists)throw new Error("Relationship not found");relationshipData=relDoc.data()||{};relationshipData.id=id;return db.collection("appData").doc(id).get()}).then(function(appDoc){appData=normalizeAppData(appDoc.exists?appDoc.data():null);showDashboard(relationshipData)})}
function handleRelationshipDoc(relDoc){var rel=relDoc.data()||{};rel.id=relDoc.id;if((rel.status||"active")==="pending"){relationshipData=rel;currentRelationshipId=rel.id;var partnerPhone=rel.partnerPhone||((rel.members||[])[1]);if(currentPhone===partnerPhone){return pendingInviteFor(currentPhone).then(function(inv){if(inv)incomingUi(inv);else showError("Pending invite found, but no invite message was available.")})}return pendingInviteFor(partnerPhone).then(function(inv){if(inv)waitingUi(inv)})}return loadRelationshipByIdPatched(rel.id)}
function createInviteRecord(relationshipId,partnerPhone,inviterName){var ref=db.collection("invites").doc(),phrase=cutePhrase(),link=inviteLink(ref.id),payload={relationshipId:relationshipId,partnerPhone:partnerPhone,inviterPhone:currentPhone,inviterName:inviterName,cuteMessage:phrase,status:"pending",link:link,createdAt:firebase.firestore.FieldValue.serverTimestamp()};return ref.set(payload).then(function(){return{id:ref.id,data:payload}})}
function createPendingRelationship(name,partnerPhone,relationshipStart,targetDate){var id=relId(currentPhone,partnerPhone),memberNames={};memberNames[currentPhone]=name;var payload={id:id,createdBy:auth.currentUser.uid,inviterPhone:currentPhone,partnerPhone:partnerPhone,members:[currentPhone,partnerPhone],memberNames:memberNames,relationshipStart:relationshipStart,targetDate:targetDate,status:"pending",createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};return db.collection("relationships").doc(id).set(payload,{merge:true}).then(function(){return db.collection("users").doc(auth.currentUser.uid).set({phone:currentPhone,name:name,relationshipId:id,lastSeenAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}).then(function(){currentRelationshipId=id;relationshipData=payload;return{id:id,data:payload}})}
createRelationship=function(){var name=document.getElementById("user-name").value.trim(),partnerPhone="+91"+document.getElementById("partner-phone").value.trim(),relationshipStart=document.getElementById("relationship-start").value,targetDate=document.getElementById("target-date").value;if(!name||!partnerPhone||partnerPhone.length<13||!relationshipStart||!targetDate){showError("Fill all fields");return}if(partnerPhone===currentPhone){showError("Cannot add yourself!");return}document.getElementById("setup-btn-text").innerHTML='<span class="loading"></span>';Promise.all([openRelationshipFor(currentPhone,null),openRelationshipFor(partnerPhone,null),pendingInviteFor(partnerPhone)]).then(function(results){var own=results[0],partner=results[1],pending=results[2];if(own)throw new Error("Your number is already linked to an active or pending relationship.");if(partner)throw new Error("That partner number is already linked with someone. Loyalty check failed.");if(pending)throw new Error("That partner number already has a pending invite.");return auth.currentUser.updateProfile({displayName:name}).then(function(){return createPendingRelationship(name,partnerPhone,relationshipStart,targetDate)}).then(function(rel){return createInviteRecord(rel.id,partnerPhone,name).then(function(invite){waitingUi(invite);showSuccess("Invite created. Share the invite link with your partner, then they can verify with Firebase OTP and accept.")})})}).catch(function(err){showError(err.message||"Unable to create relationship invite.");resetSetupButton()})};
loadUserData=function(user){db.collection("users").doc(user.uid).get().then(function(doc){if(doc.exists&&doc.data().relationshipId){return db.collection("relationships").doc(doc.data().relationshipId).get().then(function(relDoc){if(relDoc.exists)return handleRelationshipDoc(relDoc);return loadRelationshipByIdPatched(doc.data().relationshipId)})}var requestedInvite=queryInviteId();if(requestedInvite){return inviteById(requestedInvite).then(function(inv){if(inv&&inv.data.status==="pending"&&inv.data.partnerPhone===user.phoneNumber){incomingUi(inv);clearInviteQuery();return}return pendingInviteFor(user.phoneNumber).then(function(pending){if(pending)incomingUi(pending);else showAuthSection("setup-step")})})}return pendingInviteFor(user.phoneNumber).then(function(inv){if(inv){incomingUi(inv);return}return openRelationshipFor(user.phoneNumber,null).then(function(existing){if(existing){return db.collection("relationships").doc(existing.id).get().then(function(relDoc){return handleRelationshipDoc(relDoc)})}showAuthSection("setup-step")})})}).catch(function(err){console.error("Load err:",err);showAuthSection("setup-step")})};
window.acceptInviteFlow=function(){var invite=inviteState.pendingInvite;if(!invite||!currentUser){showError("No pending invite found.");return}var relRef=db.collection("relationships").doc(invite.data.relationshipId),inviteRef=db.collection("invites").doc(invite.id),userRef=db.collection("users").doc(currentUser.uid);relRef.get().then(function(doc){if(!doc.exists)throw new Error("Relationship invite no longer exists.");var rel=doc.data()||{};if((rel.status||"pending")!=="pending")throw new Error("This invite is no longer available.");var memberNames=rel.memberNames||{};memberNames[currentPhone]=currentUser.displayName||currentPhone;return relRef.set({status:"active",memberNames:memberNames,acceptedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}).then(function(){return inviteRef.set({status:"accepted",acceptedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}).then(function(){return userRef.set({phone:currentPhone,name:currentUser.displayName||"",relationshipId:invite.data.relationshipId,lastSeenAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}).then(function(){currentRelationshipId=invite.data.relationshipId;return loadRelationshipByIdPatched(invite.data.relationshipId)})}).catch(function(err){showError(err.message||"Could not accept invite.")})};
window.declineInviteFlow=function(){var invite=inviteState.pendingInvite;if(!invite){showError("No invite to decline.");return}var relRef=db.collection("relationships").doc(invite.data.relationshipId),inviterUsers=db.collection("users").where("relationshipId","==",invite.data.relationshipId).get();Promise.all([relRef.set({status:"rejected",updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}),db.collection("invites").doc(invite.id).set({status:"rejected",rejectedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}),inviterUsers]).then(function(results){results[2].forEach(function(doc){doc.ref.set({relationshipId:firebase.firestore.FieldValue.delete()},{merge:true})});showSuccess("Invite declined.");showAuthSection("setup-step")}).catch(function(err){showError(err.message||"Could not decline invite.")})};
ensureFlowCards();
})();
